log_dir: 'experiments'
exp_name: 'uniform'
device: 'cuda'
batch_size: 2048
latent_dim: 100
class_weight: 1
perturb_weight: 0.5
disc_weight: 0
iters: 1000
log_steps: 10
hist_sample_size: 10000
perturb_cfg:
  hidden_layers: 4
  dropout: 0.1
vis:
  do_vis: true
  vis_steps: 10
  vis_points: 4096
CUDNN:
  benchmark: true
  deterministic: false
  enabled: true
target:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1